apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: metrics-markedsplassen-alert
  namespace: nada
  labels:
    team: nada
spec:
  groups:
  - name: metrics-markedsplassen-alert
    rules:
    - alert: NaisjobDown
      expr: kube_job_failed{job_name=~"^metrics-markedsplassen.*", namespace="nada"} > 0
      for: 2m
      annotations:
        consequence: Dataprodukt for markedsplassen metrikker blir ikke oppdatert
        action: "Sjekk logger på https://logs.adeo.no for feil. Søk etter `container:metrics-markedsplassen* AND namespace:nada AND cluster:\"prod-gcp\"`"
        summary: |-
           Naisjob metrics-markedsplassen feiler i `prod-gcp:nada`!
           Av og til får den dårlig data fra Datamarkedsplassen, vi har retries, men det er ikke alltid det hjelper.
           Hvis neste jobb har kjørt bra så er det bare å slette den `Job`en som har feilet.
           Repo: https://github.com/navikt/metrics-dataplatform
      labels:
        namespace: nada
        severity: critical
