apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: datajegerne
  name: metrics-datajegerne
  namespace: datajegerne
spec:
  image: {{ image }}
  schedule: '00 8 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid

  gcp:
    bigQueryDatasets:
    - description: Metrikker som viser hvordan folk bruker Støtte til Etterlevelse
      name: etterlevelse
      permission: READWRITE
    - name: metrics
      permission: READ
