apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: teamdatajegerne
  name: metrics-datajegerne
  namespace: teamdatajegerne
spec:
  image: {{ image }}
  schedule: '00 4 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  backoffLimit: 6
  resources:
    limits:
      memory: 1024Mi

  gcp:
    bigQueryDatasets:
    - description: Metrikker som viser hvordan folk bruker Støtte til Etterlevelse
      name: etterlevelse
      permission: READWRITE
    - name: landing_zone
      permission: READ
    - name: behandlinger
      permission: READWRITE