name: Deploy metrics dataproduct pipeline

on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish Docker image
      run: |
        docker build . --pull --tag ${IMAGE}
        docker push ${IMAGE}

    - name: Deploy to dev-gcp
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: dev-gcp
        RESOURCE: .nais/naisjob.yaml
        VARS: .nais/dev.yaml

    - name: Deploy to prod-gcp
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: prod-gcp
        RESOURCE: .nais/naisjob.yaml,.nais/alert.yaml
        VARS: .nais/prod.yaml
